remove django.contrib.gis from INSTALLED_APPS
Removing this stops us from throwing

OSError: /var/task/libgeos_c.so:
cannot open shared object file:
No such file or directory

when we deploy

We don't need to use any of the
contrib.gis stuff in this project.